name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  NODE_VERSION: '20'

jobs:
  build:
    runs-on: ubuntu-latest

    outputs:
      build-dir: ${{ steps.set-output.outputs.build-dir }}

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Usar Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Instalar dependencias
        run: npm install

      - name: Build de la aplicación
        run: npm run build

      - name: Set output directory
        id: set-output
        run: echo "build-dir=dist" >> $GITHUB_OUTPUT

  upload-artifact:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Descargar el repo
        uses: actions/checkout@v3

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-build
          path: dist
