name: Build, Analyze and Deploy React App

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  sonarqube:
    runs-on: ubuntu-latest
    outputs:
      quality_gate_status: ${{ steps.quality_gate.outputs.quality_gate_status }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: SonarQube Scan
        id: scan
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Quality Gate Check
        id: quality_gate
        uses: sonarsource/sonarqube-quality-gate-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  deploy:
    needs: sonarqube
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Fix permissions for react-scripts
        run: chmod +x node_modules/.bin/react-scripts

      - name: Build app
        run: npm run build

      - name: Fix gh-pages permissions
        run: chmod +x node_modules/.bin/gh-pages

      - name: Configure Git author
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: Deploy to GitHub Pages
        run: npm run deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

